package uglifyjs

type AutoGenerated struct {
	Ast               bool        `json:"ast"`
	Consolidate       bool        `json:"consolidate"`
	Mangle            bool        `json:"mangle"`
	MangleToplevel    bool        `json:"mangle_toplevel"`
	NoMangleFunctions bool        `json:"no_mangle_functions"`
	Squeeze           bool        `json:"squeeze"`
	MakeSeqs          bool        `json:"make_seqs"`
	DeadCode          bool        `json:"dead_code"`
	Verbose           bool        `json:"verbose"`
	ShowCopyright     bool        `json:"show_copyright"`
	OutSameFile       bool        `json:"out_same_file"`
	MaxLineLength     int         `json:"max_line_length"`
	Unsafe            bool        `json:"unsafe"`
	ReservedNames     interface{} `json:"reserved_names"`
	Defines           struct {
	} `json:"defines"`
	LiftVars       bool `json:"lift_vars"`
	CodegenOptions struct {
		ASCIIOnly    bool `json:"ascii_only"`
		Beautify     bool `json:"beautify"`
		IndentLevel  int  `json:"indent_level"`
		IndentStart  int  `json:"indent_start"`
		QuoteKeys    bool `json:"quote_keys"`
		SpaceColon   bool `json:"space_colon"`
		InlineScript bool `json:"inline_script"`
	} `json:"codegen_options"`
	Make   bool `json:"make"`
	Output bool `json:"output"`
}
